//! Generate the algorithm documentation from the algorithms themselves (Phase 5 D3).
//!
//! The architecture's central claim is that one implementation serves three consumers: the
//! browser's step-through, the CLI's verbose mode, and the documentation. The first two are
//! visible in the product. This is the third, and until it existed the claim was an assertion
//! in a README.
//!
//! Every sentence in the generated pages is a `Step::detail` produced by running the real
//! algorithm on a real machine. Nothing here writes prose about what subset construction does;
//! it runs subset construction and prints what the implementation said while doing it. A page
//! that disagrees with the code is therefore not possible — the page *is* the code's output.
//!
//! The result is committed and CI diffs it, the same arrangement as the generated TypeScript.
//! A generated file that has drifted from its source is worse than a hand-written one, because
//! it carries a promise it is not keeping.
//!
//! Run with `./scripts/generate-docs.sh`.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use kleene_core::convert::to_regex::Order;
use kleene_core::{Traced, convert, examples, parse, thompson};

/// One generated page.
struct Page {
    file: &'static str,
    title: &'static str,
    /// The expression or machine the page is built from, named for the reader.
    input: String,
    /// Why this algorithm exists, in the two or three sentences a generator cannot produce.
    ///
    /// The *only* hand-written prose on a page. Everything below it comes from the run, and
    /// keeping the boundary sharp is what stops this file drifting back into documentation
    /// that merely happens to sit near an algorithm.
    preamble: &'static str,
    steps: Vec<String>,
    outcome: String,
}

fn page_from<T>(
    file: &'static str,
    title: &'static str,
    input: String,
    preamble: &'static str,
    traced: &Traced<T>,
    outcome: String,
) -> Page {
    Page {
        file,
        title,
        input,
        preamble,
        steps: traced
            .steps
            .iter()
            .map(|step| step.detail.clone())
            .collect(),
        outcome,
    }
}

fn render(page: &Page) -> String {
    let mut out = String::new();

    writeln!(out, "# {}", page.title).unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "<!-- Generated by `./scripts/generate-docs.sh`. Do not edit: every step below is a\n     sentence the implementation produced while running, and editing them here would make\n     this file disagree with the code it documents. -->"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{}", page.preamble).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## Worked example").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "Input: `{}`", page.input).unwrap();
    writeln!(out).unwrap();

    for (index, step) in page.steps.iter().enumerate() {
        writeln!(out, "{}. {step}", index + 1).unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "**Result.** {}", page.outcome).unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "Every line above is a `Step` returned by the same function the editor calls. The\nstep-through at [/convert](https://kleene.pranavmshukla.in/convert) renders these sentences,\n`kleene --verbose` prints them, and this page is generated from them."
    )
    .unwrap();

    out
}

fn main() {
    let out = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/algorithms");
    fs::create_dir_all(&out).expect("docs/algorithms is writable");

    let source = "(a|b)*abb";
    let ast = parse(source).expect("the worked example parses");

    let nfa = thompson(&ast);
    let dfa = convert::determinize(&nfa.result);
    let minimal = convert::minimize(&dfa.result);

    let pages = vec![
        page_from(
            "thompson.md",
            "Thompson's construction",
            source.to_string(),
            "Turns a regular expression into an ε-NFA. Each operator becomes a fragment with one\nentry and one exit, so composing them is only ever a matter of adding ε-transitions — which\nis why there is never a case analysis about how two pieces join, and why the output is larger\nthan a machine you would draw by hand.",
            &nfa,
            format!("an ε-NFA with {} states.", nfa.result.state_count()),
        ),
        page_from(
            "subset-construction.md",
            "Subset construction",
            source.to_string(),
            "Turns an ε-NFA into a DFA. Each state of the DFA stands for the *set* of NFA states the\nmachine could be in, so the non-determinism is not removed so much as accounted for. The\nworklist is the set of subsets discovered but not yet expanded, and the algorithm ends when it\nis empty.",
            &dfa,
            format!(
                "a DFA with {} states, from an ε-NFA with {}.",
                dfa.result.state_count(),
                nfa.result.state_count()
            ),
        ),
        page_from(
            "minimization.md",
            "Minimization",
            source.to_string(),
            "Merges states no string can tell apart. Partition refinement starts by separating accepting\nfrom non-accepting states — already distinguished by the empty string — and repeatedly splits\nany block whose members disagree on some symbol. The result is unique up to renaming, which is\nwhat makes minimization a reasonable way to test two machines for equivalence.",
            &minimal,
            format!(
                "{} states became {}.",
                dfa.result.state_count(),
                minimal.result.state_count()
            ),
        ),
    ];

    for page in &pages {
        let path = out.join(page.file);
        fs::write(&path, render(page)).expect("the page is writable");
        println!("wrote docs/algorithms/{}", page.file);
    }

    // State elimination is generated from a small machine on purpose: it is worst-case
    // exponential, and a page whose worked example runs to six figures of regular expression
    // teaches nothing about the method.
    let small = examples::by_key("ends_with_ab").expect("a known example");
    let eliminated = convert::to_regex_with(&small, Order::FewestEdges);
    let page = page_from(
        "state-elimination.md",
        "State elimination",
        "the `ends_with_ab` example".to_string(),
        "Turns a DFA back into a regular expression. Add a new start and accept state, then remove\nthe original states one at a time; each removal rewrites every path *through* that state as a\nsingle edge labelled with an expression. The order changes the expression but not the language,\nand no way is known to pick the order giving the shortest result.",
        &eliminated,
        format!("the expression `{}`.", eliminated.result),
    );
    fs::write(out.join(page.file), render(&page)).expect("the page is writable");
    println!("wrote docs/algorithms/{}", page.file);
}
