import { chromium } from 'playwright';
const b = await chromium.launch();
const c = await b.newContext({ colorScheme:'dark', viewport:{width:1366,height:768}, deviceScaleFactor:2 });
const p = await c.newPage(); const e=[];
p.on('pageerror',x=>e.push(String(x))); p.on('console',m=>{if(m.type()==='error')e.push(m.text())});
await p.goto('https://kleene.pranavmshukla.in',{waitUntil:'networkidle'});
await p.waitForSelector('svg[role="img"]',{timeout:15000});
await p.screenshot({path:'/private/tmp/claude-501/-Users-pranavshukla-Downloads-kleene/15218b44-f151-4af6-9934-295c9e164509/scratchpad/final.png'});
console.log('RENDER OK — console errors:', e.length? e : 'none');
await b.close();
